### ISSUE TITLE
Substrate/product ids missing from some reaction search results

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#118]
Example:
https://api.datanator.info/ftx/text_search/num_of_index/?query_message=atp&index=sabio_reaction_entries&from_=0&size=10&fields=enzyme_names&fields=ec-code&fields=substrates&fields=substrate_names&fields=products&fields=product_names&includes=ec-code&includes=enzyme_names&includes=substrate_names&includes=product_names

The test API has the same error.

**Comment by lzy7071** [comment]
This is strange because according to [line 24](https://github.com/KarrLab/datanator_frontend/blob/4467721d53d83a0984f8af60395945dccb666f0c/src/scenes/SearchResults/ReactionSearchResultsList.js#L24), the API url should have ended with [&excludes=kinlaw_id&excludes=in_metabolites](https://api.datanator.info/ftx/text_search/num_of_index/?query_message=atp&index=sabio_reaction_entries&from_=0&size=10&fields=enzyme_names&fields=ec-code&fields=substrates&fields=substrate_names&fields=products&fields=product_name&excludes=kinlaw_id&excludes=in_metabolites) without the `excludes={}` contained in the URL.

**Comment by lzy7071** [comment]
It seems the production server already reflects the editing https://datanator.info/search/atp/Escherichia%20coli%20E1002/. The error indicated by Airbrake was from an old preview link. I don't know how to disable Airbrake from testing older preview links.

**Comment by lzy7071** [comment]
Closing because API endpoint used in production frontend is correct.
