### ISSUE TITLE
How can I retrieve metadata about an OrthoDB group (i.e. name)?

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#125]
For KO groups, we used `kegg/get_meta/?kegg_ids=`. This provided
- name
- EC code

What is the right endpoint to use for OrthoDB groups?

**Comment by lzy7071** [comment]
We do have a collection for orthodb information. However, it only contains `orthodb_id` and `orthodb_name` pairs because orthodb datafile didn't provide x-ref information on EC (probably is many-to-many relationship). I made it in such a way that all protein records should contain `orthodb_id` and `orthodb_name` but https://github.com/KarrLab/datanator_rest_api/issues/122 pointed out there were cases where `orthodb_name` was missing.

**Comment by jonrkarr** [comment]
Just the name is fine. What's the endpoint to lookup the name of each OrthoDB group by its id?

**Comment by lzy7071** [comment]
http://testapi.datanator.info/kegg/get_meta/?kegg_ids=567019at2&size=10 works now.

**Comment by jonrkarr** [comment]
Looks good
