### ISSUE TITLE
Non-coding RNA search results should be aggregated

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#130]
In the example below, `tRNA-Ala` appears twice as two hits in the search results. This should be aggregated together so that users don't see the same result repeated twice in the search results.
https://testapi.datanator.info/ftx/text_search/gene_ranked_by_ko/?query_message=trna%20ala&from_=0&size=10&fields=definition

Here's the full endpoint that the frontend is currently using.
https://testapi.datanator.info/ftx/text_search/gene_ranked_by_ko/?query_message=trna%20ala&from_=0&size=10&fields=orthodb_id&fields=orthodb_name&fields=gene_name&fields=gene_name_alt&fields=gene_name_orf&fields=gene_name_oln&fields=entrez_id&fields=protein_name&fields=entry_name&fields=uniprot_id&fields=definition&fields=ec_number

**Comment by jonrkarr** [comment]
(Note for me) Here's the frontend URL that is affected by this issue: http://localhost:3000/search/trna%20ala/

**Comment by lzy7071** [comment]
Yes. I need to fix the tokenization https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-tokenizers.html. This is related to https://github.com/KarrLab/datanator_rest_api/issues/127#issuecomment-706275800

**Comment by lzy7071** [comment]
Note to self:
tRNAs are now aggregated using `orthodb_id.keyword` (https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-fields.html).
Need to see why rRNA is not searchable, more than likely caused by tokenization options.

**Comment by lzy7071** [comment]
I thought the issue stems from how Elasticsearch's standard tokenizer deals with `.` in string was different from the tokenizer for `fieldtype` `text`. After a few hours tinkering with analyzers and tokenizers and such, I realized somehow the record with `orthodb_id` just wasn't transferred to Elasticsearch, because https://testapi.datanator.info/ftx/text_search/gene_ranked_by_ko/?query_message=LSU5.8S&from_=0&size=10&fields=orthodb_id&fields=definition returns the proper result.
https://testapi.datanator.info/ftx/text_search/gene_ranked_by_ko/?query_message=LSU5.8S&from_=0&size=10&fields=orthodb_id&fields=_id now works.

**Comment by jonrkarr** [comment]
Looks good. Thanks for persisting!
