### ISSUE TITLE
Add number of full text matches to full text search results

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#17]

**Comment by lzy7071** [comment]
For categories other than "protein," the number of matches can be found under "index_total:{}" object when using "ftx/text_search/num_of_index/?"
For protein category, the "total: {}" object is already there. See the [schema definition](https://api.datanator.info/#/FTX/get_ftx_text_search_protein_ranked_by_ko_) for details.

**Comment by jonrkarr** [comment]
Can you clarify where the information is in the output? I don't see `index_total` in the output for the URL below.

Also, why are the `from_` and `size` parameters needed? What I'm looking for is the total number of matches (roughly size * the number of pages).

https://api.datanator.info/ftx/text_search/num_of_index/?query_message=glucose&index=metabolites_meta&from_=0&size=10&fields=protein_name&fields=synonyms&fields=enzymes&fields=ko_name&fields=gene_name&fields=name&fields=enzyme_name&fields=product_names&fields=substrate_names&fields=enzymes.subunit.canonical_sequence&fields=species

**Comment by lzy7071** [comment]
Sorry I forgot to deploy the new API after circle was done testing. It should be up within a few minutes.
The pagination parameters are there because it is the same call that is used for the intermediary page, so a separate call is not needed (one call for both displaying the intermediary page and the total count). They don't affect the total count at all.

**Comment by lzy7071** [comment]
There should be an object 
"metabolites_meta_total": {"relation": "eq", "value": 52}

**Comment by jonrkarr** [comment]
Is the number of protein results in `sum_other_doc_count`?

**Comment by lzy7071** [comment]
It should be either "from_ + size + sum_other_doc_count" or "size + sum_other_doc_count" I haven't tested it.
Protein's total is different from the others because it involves pipeline aggregation and bucket sort.

-------- Original Message --------

**Comment by lzy7071** [comment]
Protein's total doc count is different from the other because it involves pipeline aggregation and bucket sorting. It should be "sum of all docs in the buckets from the response" + "sum_other_doc_count." This will give the use the total number of protein records found.
I'll check if there is an easier way to get the total sum directly from the pipeline aggregation.

**Comment by jonrkarr** [comment]
I just need a JavaScript function or even just pseudo code for how to
calculate it.

**Comment by lzy7071** [comment]
sum = sum_other_doc_count
for bucket in buckets:
    sum += bucket['doc_count']
return sum

**Comment by jonrkarr** [comment]
I think this counts the number of proteins. How can I calculate the number of matching ortholog groups?

**Comment by lzy7071** [comment]
I have added an additional second object  
"total_buckets": {
    "value": n
 }"
where n is the total number of buckets, i.e. number of orthologue groups. It should be deployed in 5 min.

**Comment by lzy7071** [comment]
There is now an additional object   "total_buckets": {
    "value": n
  }, where n is the total number of buckets, i.e. ortholog groups.

**Comment by jonrkarr** [comment]
Looks great.
