### ISSUE TITLE
Create endpoints which just return metadata about metabolites, RNA, proteins, and reactions

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#27]
This may be redundant with #26.

These endpoints can be created by splitting the functionality of the current data endpoints.

This plan would make it easier to scale up the UI to display multiple types of data per type of biochemical entity (e.g., RNA abundances and half-lives; protein abundances, half-lives, and DNA binding sites). This would enable each UI component to separately request the data it needs, avoiding the need to pass data among UI components. This would also make the REST endpoints more flexible for users to compose into sophisticated analyses.

1. Create endpoints which just return metadata (e.g., name, description, links to other databases, etc.)
    - Metabolite
    - RNA
    - Protein
    - Reaction
2. Metadata can be removed from the data end points (metabolite concentration, RNA half-life, protein abundance, reaction rate constant)

**Comment by lzy7071** [comment]
Change projection options in datanator_query_python

**Comment by lzy7071** [comment]
Metabolite
- [/meta/?inchi_key={}](https://api.datanator.info/metabolites/meta/?inchi_key=UHDGCWIWMRVCDJ-XVFCMESISA-N)

**Comment by yosefdroth** [comment]
I have an issue related to an issue Jonathan brought up in the frontend - https://github.com/KarrLab/datanator_frontend/issues/126

Right now, all the metadata on the frontend page comes from the /metabolites/concentration/ endpoint. This endpoint returns data on all similar molecules to the queried molecules (e.g. if you [queried for TDP-Glucose](https://api.datanator.info/metabolites/concentration/?metabolite=TDP-Glucose&abstract=true), it will return data about the structurally similar Uridine 5'-diphosphate). However, at the moment, it will only return data for metabolites with concentration data (so it does not return any information about TDP-Glucose because it has no concentration data, even though we do have metadata). 

For the endpoint /metabolites/concentration/, can it have the option of returning metadata for a specific molecule (e.g. TDP-Glucose) even if it has no concentration data? Perhaps we can use abstract=false to mean that it should only return information about the queried molecule, and it should return it whether or not it has concentration data. This way, the DataTable can query /metabolites/concentration/ with abstract=true and it will get all of the concentration data, and the Metadata section can use abstract=false, and just get the metadata.

I was looking into using the /meta/?inchi_key={} endpoint, however its currently missing a lot of the meta information that /metabolites/concentration/ has. We could potentially expand the  /meta/?inchi_key={} endpoint, but I think it would likely be easier to use /metabolites/concentration/ because all of the data is already there.

**Comment by lzy7071** [comment]
I have changed the returned object of [/metabolite/meta/inchi_key={}](http://api.datanator.info/metabolites/meta/?inchi_key=XCCTYIAWTASOJW-XVFCMESISA-N) to include all the meta data.

I chose to edit the endpoint above because I never understood what the `abstract` option did in [molecule_name_query](https://github.com/KarrLab/datanator_query_python/blob/92692a5107bd0e832669a97f1d56dcff32c40aed/datanator_query_python/query/front_end_query.py#L101), or quite frankly, what `molecule_name_query` itself did. It seems to me toggling `abstract` between `True` and `False` actually causes different [behaviors](https://github.com/KarrLab/datanator_query_python/blob/92692a5107bd0e832669a97f1d56dcff32c40aed/datanator_query_python/query/front_end_query.py#L116).

I apologize for the intermittent up/down of the API service in the past hour, I was having a lot of problems with Pipfile and pipenv but it should be good now.

**Comment by yosefdroth** [comment]
Thanks! This is great, it seems like all the information is here. 

Can the query be a molecule name, rather than an inchi_key? Right now, the frontend makes the queries based off the name of the molecule.

**Comment by lzy7071** [comment]
> Thanks! This is great, it seems like all the information is here.
> 
> Can the query be a molecule name, rather than an inchi_key? Right now, the frontend makes the queries based off the name of the molecule.

[/metabolite/meta/?_input={}](http://api.datanator.info/metabolites/meta/?_input=ATP) can be used to accomplish that.

**Comment by lzy7071** [comment]
Each category now has its own meta collection / index.
