### ISSUE TITLE
Protein search results occasionally return non-sensical orthology groups with concatenated names

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#39]
Example `K02778K02779`

https://api.datanator.info/ftx/text_search/protein_ranked_by_ko/?query_message=glucose&from_=50&size=10&fields=protein_name&fields=synonyms&fields=enzymes&fields=ko_name&fields=gene_name&fields=name&fields=enzymes.enzyme.enzyme_name&fields=enzymes.subunit.canonical_sequence&fields=species

**Comment by lzy7071** [comment]
This is due to the fact that one protein can belong to several KO groups but I still needed to keep the field as string type in ES and MongoDB. 
I have changed the returned data types from rest API for both field "key" and "ko_number" to array to resolve the issue. However, the data transformation utilities in the frontend package might need to make corresponding changes to reflect the change in data types.
