### ISSUE TITLE
RNA half life no longer working

### ISSUE THREAD

**Issue by yosefdroth** [KarrLab/datanator_rest_api#48]
For example,

https://api.datanator.info/ftx/text_search/num_of_index/?query_message=alchohol%20deydrogenase&index=rna_halflife&from_=0&size=10&fields=protein_name&fields=synonyms&fields=gene_name&fields=name&fields=enzymes.enzyme.enzyme_name

**Comment by lzy7071** [comment]
> For example,
> 
> https://api.datanator.info/ftx/text_search/num_of_index/?query_message=alchohol%20deydrogenase&index=rna_halflife&from_=0&size=10&fields=protein_name&fields=synonyms&fields=gene_name&fields=name&fields=enzymes.enzyme.enzyme_name

Pretty sure it was because there wasn't a protein named `alcohol dehydrogenase` in the collection. I trield [`dehydrogenase`](http://api.datanator.info/ftx/text_search/num_of_index/?query_message=dehydrogenase&index=rna_halflife&from_=0&size=10&fields=protein_names&fields=halflives.accession_id&fields=identifier
) and it worked. Also, the relevant field names for `rna_halflife` collection is `protein_names`, `halflives.accession_id`, and `identifier`.
