### ISSUE TITLE
Taxonomic distances are incorrect for same species in metabolite concentrations

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#74]
Example:
https://api.datanator.info/metabolites/concentrations/similar_compounds/?inchikey=HSCJRCZFDFQWRP-RDKQLNKOSA-N&threshold=0.6&target_species=Escherichia%20coli&taxon_distance=true

Concentrations observed with species "Escherichia coli" (NCBI taxonomy id 562) have distance 1 (genus). The distance should be 0 (species).

**Comment by jonrkarr** [comment]
Taxonomic distances appear to be correct for RNA half-lives

**Comment by lzy7071** [comment]
Because the way I determine the length is by using the length of an ancestors array, subtract that by the index at which the last common ancestor is found.

Example:
- Species A has ancestors `[a, b, c, d, e, f, g]`
- Species B has ancestors `[a, b, c, d, e, h, i, j]`
- The "closest" common ancestor is `e`, the index is of `e` is 4.
- Species A has distance of `7 - 4 = 3`, and B has a distance of `8 - 4 = 4`

Therefore, if two species are exactly the same, the length will be `1` since they have 0-indexed array.
RNA half-life also reflects this implementation, see [Saccharomyces cerevisiae S288C](https://api.datanator.info/rna/halflife/get_info_by_ko/?ko_number=K13954&_from=0&size=1000&taxon_distance=true&species=Saccharomyces%20cerevisiae%20S288C)

**Comment by jonrkarr** [comment]
Something is off because the textual distance names don't line up with the taxonomy filter. I need to look into this further.

**Comment by jonrkarr** [comment]
I think we figured out the issue. The taxonomic distance calculations aren't correctly dealing with two edge cases:
- [ ] The target and measured taxa are the same
- [ ] The target taxon is an ancestor of the measured taxon

Examples:
- Target and measured are the same taxon:
  - If target=`Escherichia coli`, measured=`Escherichia coli` the distance is `1`. The distance should be `0`.
- Target taxon is an ancestor of the measured taxon:
  - If target=`Escherichia coli`, measured=`Escherichia coli K-12` the distance should be `0`.
  - If target=`Escherichia`, measured=`Escherichia coli` the distance should be `0`.

**Comment by jonrkarr** [comment]
This is now covered by KarrLab/datanator_query_python#11
