### ISSUE TITLE
Tanimoto similarity is missing for some metabolites

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#75]
Example: first entry of
https://api.datanator.info/metabolites/concentrations/similar_compounds/?inchikey=RNBGYGVWRKECFJ-ARQDHWQXSA-N&threshold=0.6&taxon_distance=false

I suspect these correspond to metabolites measured in individual journal articles.

**Comment by lzy7071** [comment]
> Example: first entry of
> https://api.datanator.info/metabolites/concentrations/similar_compounds/?inchikey=RNBGYGVWRKECFJ-ARQDHWQXSA-N&threshold=0.6&taxon_distance=false
> 
> I suspect these correspond to metabolites measured in individual journal articles.

It was because the first entry is the metabolite itself, which wasn't included in the original `/metabolites/concentrations/similar_compounds/` endpoint. I still think a two-call operation, one for the metabolite itself with `/metabolite/concentrations/?inchikey={}` and the other with `/metabolites/concentrations/similar_compounds/` to fill the data table is a better approach. 
I just manually added the `similarity_score` of value `1.0` in.

**Comment by jonrkarr** [comment]
I forgot about that. Thanks.
