### ISSUE TITLE
Some metabolite concentrations lack references

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#77]
Example: entry with concentration 2122.0 in
https://api.datanator.info/metabolites/concentrations/similar_compounds/?inchikey=RFSUNEUAIZKAJO-ARQDHWQXSA-N&threshold=0.6&taxon_distance=false

**Comment by lzy7071** [comment]
> Example: entry with concentration 2122.0 in
> https://api.datanator.info/metabolites/concentrations/similar_compounds/?inchikey=RFSUNEUAIZKAJO-ARQDHWQXSA-N&threshold=0.6&taxon_distance=false

This is because the information was lacking from the source database, in this case [YMDB D-Glucose, second entry of `Intracellular Concentrations`](http://www.ymdb.ca/compounds/YMDB00286). I think this can be resolved by indicating the source as either `YMDB [name of metabolite]` or `ECMDB [name of metabolite]`. To determine from which of the two the concentration information came, one just needs to look at the `ncbi_taxonomy_id`. Because the concentration parsed from primary sources by us will always have reference information.

**Comment by jonrkarr** [comment]
Indicating ECMDB or YMDB is great. Here's one potential way to organize the references:
```
...
"reference": {
    "namespace": "ecmdb",
    "id": "<ECMDB id>"
}
...
```

Values for namespace (chosen to align with Identifiers.org)
- `doi`
- `ecmdb`
- `pubmed`
- `ymdb`
- `text` (for other miscellaneous references)

**Comment by jonrkarr** [comment]
Please let me know how you decide to organize the references so I can update the frontend if needed.

**Comment by lzy7071** [comment]
> Please let me know how you decide to organize the references so I can update the frontend if needed.

It is now in the following schema:
```
...
"reference": {
    "namespace": "", ("pubmed", "doi", "ecmdb", or "ymdb")
    "id": "",
    "text": ""
}
...  
Do note that when namespace is "pubmed", id can be null, the information is just not there from the original database. However, in that case, "text" can be used.
```

**Comment by jonrkarr** [comment]
I updated the frontend accordingly.
