### ISSUE TITLE
What do the numbers mean in the taxonomic rank calculations?

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#79]
Example:
https://api.datanator.info/taxon/canon_rank_distance_by_name/?name=Bacillus%20subtilis

```
[
  {"Bacillus subtilis": 0},
  {"Bacillus": 2, "rank": "genus" },
  {"Bacillaceae": 3, "rank": "family"},
  {"Bacillales": 4, "rank": "order"},
  {"Bacilli": 5, "rank": "class"},
  {"Firmicutes": 6, "rank": "phylum"},
  {"Bacteria": 8, "rank": "superkingdom"},
  {"cellular organisms": 9}
]
```

- Are the numbers the distances when including the non-canonical ranks? 
- Are the canonical distances the indices of the canonical ranks in the above array?

**Comment by lzy7071** [comment]
I can explain this better with the given example:
An organism named `Bacillus subtilis` has ancestors `["cellular organisms", "Bacteria", "Terrabacteria group", "Firmicutes", "Bacilli", "Bacillales", "Bacillaceae", "Bacillus", "Bacillus subtilis group"]`, all of which are not canonically ranked.
`Bacillus subtilis` itself has a rank of `species`, which is canon. Therefore, including itself, the distance (including non-canonical ranks) between canonically ranked ancestors and `Bacillus subtilis` is
```
[
  {"Bacillus subtilis": 0},
  {"Bacillus": 2, "rank": "genus" },
  {"Bacillaceae": 3, "rank": "family"},
  {"Bacillales": 4, "rank": "order"},
  {"Bacilli": 5, "rank": "class"},
  {"Firmicutes": 6, "rank": "phylum"},
  {"Bacteria": 8, "rank": "superkingdom"},
  {"cellular organisms": 9}
], where rank indicates the canonical rank of the ancestor.
```
The canonical distance is just the index of the object containing the canonical ancestor.
This endpoint is not used anymore because we are not interested in non-canonical distances.

**Comment by jonrkarr** [comment]
Thanks. I think I understand this now. The frontend was using the numbers in the data structure when it should be using the indices.
