### ISSUE TITLE
Some gene search results have KEGG orthology id `nan`

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#80]
Example: 6th bucket of 
https://api.datanator.info/ftx/text_search/protein_ranked_by_ko/?query_message=tyr&from_=0&size=10&fields=ko_name&fields=ko_number&fields=gene_name&fields=gene_name_alt&fields=gene_name_orf&fields=gene_name_oln&fields=entrez_id&fields=protein_name&fields=entry_name&fields=uniprot_id&fields=ec_number

**Comment by lzy7071** [comment]
> Example: 6th bucket of
> https://api.datanator.info/ftx/text_search/protein_ranked_by_ko/?query_message=tyr&from_=0&size=10&fields=ko_name&fields=ko_number&fields=gene_name&fields=gene_name_alt&fields=gene_name_orf&fields=gene_name_oln&fields=entrez_id&fields=protein_name&fields=entry_name&fields=uniprot_id&fields=ec_number

In this case, "nan" is actually just a string in the database so it should still be JSON serializable.

**Comment by jonrkarr** [comment]
In that example, the KO number is `nan`, but this isn't a valid KO id.

**Comment by lzy7071** [comment]
> In that example, the KO number is `nan`, but this isn't a valid KO id.

Oh, that's because some protein isn't annotated with a KO id on uniprot. 
Without KO: [Q815Y0](https://www.uniprot.org/uniprot/Q815Y0) 
With KO [F1NW29](https://www.uniprot.org/uniprot/F1NW29)

`"nan"` is there to indicate the protein is not annotated with KO.

**Comment by jonrkarr** [comment]
Can we exclude these from the full text search results? The reason to exclude them is that the gene page won't be able to display them since there's no KO id. If we include them, the broken links will seem like an error to users.

For now, the frontend is skipping search results with KO id = `nan`. But this causes the frontend to display fewer results than users will think it should, which also seems like a (subtle) error (i.e. the frontend says that its showing 10 results, but actually only shows 9 because the 10th has KO id `nan`).

**Comment by lzy7071** [comment]
> Can we exclude these from the full text search results? The reason to exclude them is that the gene page won't be able to display them since there's no KO id. If we include them, the broken links will seem like an error to users.
> 
> For now, the frontend is skipping search results with KO id = `nan`. But this causes the frontend to display fewer results than users will think it should, which also seems like a (subtle) error (i.e. the frontend says that its showing 10 results, but actually only shows 9 because the 10th has KO id `nan`).

I can see two ways of going about this,

1. Skipping  KO id = `nan` as you suggested. However, because the total number of buckets is determined prior to getting KO information, it will result in the number of returned buckets mismatching the number given in `size` parameter. In addition, we are skipping a record that is actually relevant to the user intent. For instance, the protein returned from the link given with KO id = `nan` is named "Ser/Thr and Tyr protein phosphatase (Dual specificity)"

2. I have already included an additional field named `protein_name` in `_source` object. In the case of KO id = `nan`, we can use `protein_name` as the name on the `Genes` intermediate page and `_id` for the secondary information field. But going from intermediate page to a gene-specific page for that particular entry will have to use a different endpoint, [http://api.datanator.info/proteins/meta/meta_combo/?uniprot_id=Q815Y0](http://api.datanator.info/proteins/meta/meta_combo/?uniprot_id=Q815Y0), since KO is not available. 

Let me know which one you prefer.

**Comment by jonrkarr** [comment]
(2) is better for the reasons you outlined

**Comment by jonrkarr** [comment]
I integrated this into the gene search results and gene data pages.
