### ISSUE TITLE
Reaction kinetics endpoint is no longer working

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#82]
https://api.datanator.info/reactions/kinlaw_by_name/?_from=0&size=1000&bound=tight&substrates=H2O%7CD-Glucose%206-phosphate&products=Phosphate%7CD-Glucose

**Comment by lzy7071** [comment]
> https://api.datanator.info/reactions/kinlaw_by_name/?_from=0&size=1000&bound=tight&substrates=H2O%7CD-Glucose%206-phosphate&products=Phosphate%7CD-Glucose

The link provided is working on my end.

**Comment by jonrkarr** [comment]
It seems to be failing intermittently. I don't know why.

**Comment by lzy7071** [comment]
> It seems to be failing intermittently. I don't know why.

I suspect it has something to do with the `size` being set to `1000` and the search result being in / not in cache. Why does the `size` need to be `1000`?

**Comment by yosefdroth** [comment]
This is to make sure that it has all of the data points. We could make it smaller, but we should ensure that we don't leave anything out. 

The data-tables themselves aren't really designed for pagination as it it, because we want to display all the data at once. This is to allow the user to see the distribution of data in the stats column

**Comment by lzy7071** [comment]
> This is to make sure that it has all of the data points. We could make it smaller, but we should ensure that we don't leave anything out.
> 
> The data-tables themselves aren't really designed for pagination as it it, because we want to display all the data at once. This is to allow the user to see the distribution of data in the stats column

If the stat summary is the only reason preventing the table from having pagination, would an endpoint that provide summary (count, mean, std, etc.) for all available kinetic constants enable pagination thus eliminating the need to set `size` to `1000`? Because each document returned by the endpoint `/reactions/kinlaw_by_name/` contains a lot of information, most of which is not needed for the summary calculation.

**Comment by jonrkarr** [comment]
1,000 doesn't seem like a particularly large number. This particular query only involves 37 results.

Is there any logging which could provide insight?

**Comment by lzy7071** [comment]
> 1,000 doesn't seem like a particularly large number. This particular query only involves 37 results.
> 
> Is there any logging which could provide insight?

Heroku logs doesn't really provide much insight into the problem:
```
2020-05-22T00:52:49.060556+00:00 heroku[router]: at=info method=GET path="/reactions/kinlaw_by_name/?_from=0&size=1000&bound=tight&substrates=H2O%7CD-Glucose%206-phosphate&products=Phosphate%7CD-Glucose" host=api.datanator.info request_id=2c3ca560-80f5-45a6-a0c3-599563722bed fwd="XXX" dyno=web.1 connect=1ms service=1873ms status=200 bytes=752319 protocol=https
2020-05-22T00:52:49.042682+00:00 app[web.1]: 10.37.232.57 - - [22/May/2020:00:52:49 +0000] "GET /reactions/kinlaw_by_name/?_from=0&size=1000&bound=tight&substrates=H2O%7CD-Glucose%206-phosphate&products=Phosphate%7CD-Glucose HTTP/1.1" 200 752131 "https://github.com/KarrLab/datanator_rest_api/issues/82" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
```
Also, I remembered I changed the process to `aggregation` so the performance is much improved and the size count shouldn't really matter any more.

**Comment by lzy7071** [comment]
Look into MongoDB logs for possible clarifications.

**Comment by jonrkarr** [comment]
Closing because the endpoint changed significant, and this may no longer be relevant
